<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJRCIJmI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJRCIJmI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJRCIJmI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJRCIJmI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJRCIJmI\appAppKernelProdContainer([
    'container.build_hash' => 'JRCIJmI',
    'container.build_id' => 'dbc5a518',
    'container.build_time' => 1713863551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJRCIJmI');
