<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZz74Fqp\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZz74Fqp/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZz74Fqp.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZz74Fqp\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZz74Fqp\appAppKernelProdContainer([
    'container.build_hash' => 'Zz74Fqp',
    'container.build_id' => '3ca3a630',
    'container.build_time' => 1713863355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZz74Fqp');
